#! /bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <src-dir> <dst-dir>"
  echo "e.g.: $0 inputs_leda data"
  exit 1
fi
src=$1
dst=$2

phoneset=$src/phoneset.txt # monophone_map_leda.txt
lex=$src/lexicon_autogen.1 # pron with variants, in int form, generated by G2P

for f in $phoneset $lex; do
    [ -f $f ] || { echo "$f does not exist"; exit 1; }
done

export LC_ALL=C
odir=$dst # /local/dict
mkdir -p $odir  # data/local/dict

# Reformat tabs to space and rm variant numbers
awk -F'\t' '{if ($1!="" && $4!="") print $1"("$2")",$3,$4}' $lex | sed 's/(0)//g' | sort -k1 | uniq > $odir/lexiconp.intt
ls -l $odir/lexiconp.intt
# Rm probabilities
awk '{$2=""; print}' $odir/lexiconp.intt > $odir/lexicon.intt
awk '{print $2,$1}' $phoneset  > $odir/phonemap.txt
utils/int2sym.pl -f 3- $odir/phonemap.txt $odir/lexiconp.intt | sed 's/ 0.000000 / 0.000001 /' > $odir/lexiconp.txt
# The sed filter rounds up 0.0's to prevent utils/validate_dict_dir.pl from complaining about 0.0's.
# It's only needed for field 2, but the general tool utils/int2sym.pl shouldn't be customized to do that.

echo 'SIL SPN NSN' > $odir/extra_questions.txt 
cat <<EOF > $odir/silence_phones.txt
SIL
SPN
NSN
EOF

awk '{print $2}' $phoneset > $odir/nonsilence_phones.txt
echo 'SIL' > $odir/optional_silence.txt

cat <<EOT >> $odir/lexiconp.txt
SIL 1.0 SIL
!SIL 1.0 SIL
<SPOKEN_NOISE> 1.0 SPN
<UNK> 1.0 SPN
<NOISE> 1.0 NSN
EOT

awk '{$2=""; print}' $odir/lexiconp.txt > $odir/lexicon.txt
